export type GetCreditMemosMagentoResponse = {
  items: CreditMemoItem[];
  total_count: number;
};

type CreditMemoItem = {
  adjustment?: number | null;
  adjustment_negative?: number | null;
  adjustment_positive?: number | null;
  base_adjustment?: number | null;
  base_adjustment_negative?: number | null;
  base_adjustment_positive?: number | null;
  base_currency_code?: string | null;
  base_discount_amount?: number | null;
  base_grand_total?: number | null;
  base_discount_tax_compensation_amount?: number | null;
  base_shipping_amount?: number | null;
  base_shipping_incl_tax?: number | null;
  base_shipping_tax_amount?: number | null;
  base_subtotal?: number | null;
  base_subtotal_incl_tax?: number | null;
  base_tax_amount?: number | null;
  base_to_global_rate?: number | null;
  base_to_order_rate?: number | null;
  billing_address_id?: number | null;
  created_at: string;
  discount_amount?: number | null;
  discount_description?: string | null;
  entity_id?: number | null;
  global_currency_code?: string | null;
  grand_total?: number | null;
  discount_tax_compensation_amount?: number | null;
  increment_id: string;
  invoice_id?: number | null;
  order_currency_code?: string | null;
  order_id: number;
  shipping_address_id?: number | null;
  shipping_amount?: number | null;
  shipping_incl_tax?: number | null;
  shipping_tax_amount?: number | null;
  state?: number | null;
  store_currency_code: string;
  store_id: number;
  store_to_base_rate?: number | null;
  store_to_order_rate?: number | null;
  subtotal?: number | null;
  subtotal_incl_tax?: number | null;
  tax_amount?: number | null;
  transaction_id?: string | null;
  updated_at?: string | null;
  comments?: string[] | null;
  extension_attributes?: {
    order_increment_id?: string | null;
    external_order_id?: string | null;
  } | null;
  items: OrderItem[];
};

type OrderItem = {
  base_cost?: number | null;
  base_discount_tax_compensation_amount?: number | null;
  base_price?: number | null;
  base_price_incl_tax?: number | null;
  base_row_total?: number | null;
  base_row_total_incl_tax?: number | null;
  base_tax_amount?: number | null;
  base_weee_tax_row_disposition?: number | null;
  entity_id?: number | null;
  discount_tax_compensation_amount?: number | null;
  name?: string | null;
  order_item_id: number;
  parent_id?: number | null;
  price?: number | null;
  price_incl_tax?: number | null;
  product_id?: number | null;
  qty: number;
  row_total?: number | null;
  row_total_incl_tax?: number | null;
  sku: string;
  sap_code: string;
  tax_amount?: number | null;
  weee_tax_applied?: string | null;
  weee_tax_applied_row_amount?: number | null;
  weee_tax_row_disposition?: number | null;
};
