import { GetCreditMemosMagentoResponse, GetCreditMemosResponse } from '../types';

export const TEST_GET_CREDIT_MEMOS_RESPONSE: GetCreditMemosResponse = {
  success: true,
  data: [
    {
      sales_order_increment_id: 'ABC123',
      external_order_id: '',
      increment_id: 'ABC321',
      total_refunded: 46.35,
      tax_refunded: 0,
      transaction_id: 'ABGDFG43534-capture-refund',
      created_at: '2023-01-27 12:23:07',
      Items: [
        {
          sku: '4444191',
          sap_code: '4444191',
          qty_refunded: 1,
          row_total_incl_tax: 46.35,
          tax_amount: 0,
        },
      ],
    },
  ],
};

export const TEST_GET_CREDIT_MEMOS_MAGENTO_RESPONSE: GetCreditMemosMagentoResponse = {
  items: [
    {
      adjustment: 0,
      adjustment_negative: 0,
      adjustment_positive: 0,
      base_adjustment: 0,
      base_adjustment_negative: 0,
      base_adjustment_positive: 0,
      base_currency_code: 'EUR',
      base_discount_amount: 0,
      base_grand_total: 46.35,
      base_discount_tax_compensation_amount: 0,
      base_shipping_amount: 0,
      base_shipping_incl_tax: 0,
      base_shipping_tax_amount: 0,
      base_subtotal: 46.35,
      base_subtotal_incl_tax: 46.35,
      base_tax_amount: 0,
      base_to_global_rate: 0.8778,
      base_to_order_rate: 1,
      billing_address_id: 237022,
      created_at: '2023-01-27 12:23:07',
      discount_amount: 0,
      discount_description: 'Spent 15 amount, get 1 product Free',
      entity_id: 17,
      global_currency_code: 'GBP',
      grand_total: 46.35,
      discount_tax_compensation_amount: 0,
      increment_id: 'ABC321',
      invoice_id: 656,
      order_currency_code: 'EUR',
      order_id: 125199,
      shipping_address_id: 237021,
      shipping_amount: 0,
      shipping_incl_tax: 0,
      shipping_tax_amount: 0,
      state: 2,
      store_currency_code: 'EUR',
      store_id: 5,
      store_to_base_rate: 0,
      store_to_order_rate: 0,
      subtotal: 46.35,
      subtotal_incl_tax: 46.35,
      tax_amount: 0,
      transaction_id: 'ABGDFG43534-capture-refund',
      updated_at: '2023-01-27 12:23:07',
      items: [
        {
          base_cost: null,
          base_discount_tax_compensation_amount: 0,
          base_price: 46.35,
          base_price_incl_tax: 46.35,
          base_row_total: 46.35,
          base_row_total_incl_tax: 46.35,
          base_tax_amount: 0,
          base_weee_tax_row_disposition: 0,
          entity_id: 22,
          discount_tax_compensation_amount: 0,
          name: '13 Extra Oloroso Sherry Cask Scotch Whisky Scotland',
          order_item_id: 614828,
          parent_id: 17,
          price: 46.35,
          price_incl_tax: 46.35,
          product_id: 235892,
          qty: 1,
          row_total: 46.35,
          row_total_incl_tax: 46.35,
          sku: '4444191',
          sap_code: '4444191',
          tax_amount: 0,
          weee_tax_applied: '[]',
          weee_tax_applied_row_amount: 0,
          weee_tax_row_disposition: 0,
        },
      ],
      comments: [],
      extension_attributes: {
        order_increment_id: 'ABC123',
        external_order_id: '',
      },
    },
  ],
  total_count: 1,
};
